language: node_js
matrix:
  include:
    - node_js: '6'
    - node_js: '7'
    - node_js: '8'
    - node_js: '10'
      env: PUBLISH_PACKAGE=ON

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: prettier
      if: env(PUBLISH_PACKAGE) = ON
      script: npm run format:check
    - stage: lint
      if: env(PUBLISH_PACKAGE) = ON
      script: npm run lint:check
    - stage: test
      script:
        - npm run prebuild
        - npm run build
        - npm run webbuild
        - npm run test
        - npm run e2e
    - stage: examples
      if: env(PUBLISH_PACKAGE) = ON
      script:
        - cd example ;
          bash configure.sh ;
          bash run.sh ;
          cd ..
    - stage: legacy node
      if: env(PUBLISH_PACKAGE) = ON
      script:
        - NODE_VERSION=`node --version | cut -dv -f2`
        - nvm install 0.12 ;
          node --version ;
          node --eval "var fc = require('./lib/fast-check'); fc.assert(fc.property(fc.string(), function(s) { return s === s; }))" ;
        - nvm use "${NODE_VERSION}" ;
    - stage: deploy
      if: env(PUBLISH_PACKAGE) = ON
      script: skip
      after_success: npm run coverage
      deploy:
        provider: npm
        email: npm@dubien.org
        skip_cleanup: true
        api_key:
          secure: U25V+vyJQn14dxiWUJ5bcsXIVM5gLxNmRvmJ8FgwyRST1tqvPk0x71rq1n0rwXJTO3aLMfEAz6499bG9MKNlwDwFBCRqDCWicbaXgAWqplaGbS3pI9EtA6aleLaS2SRET2jAT1piWtGPaXNdIQOS1ZaM+CG5RbKu0SoFDq25lPh2CrktqoR0nb2YKneWw8W7QGCuOpm11i5uLKs+7vhKOp8MVwRksHm3QgDX/+kbLVik71FEbmfn2DMna4RLCUKxeayX9/6dx+ZCD00EY5POaKNFzo29HvFaNRwNdUcPZYE97ZBDqgbs2z9KHQljBVB4cYP1lEGgTbpmPOJ9Oj8boGlf+TF/3bSK/tM0a/CKwp/L8+Fd7NSpMlLCAiMDje/3DQ5PgI5LojQzHe4zMCZO5rphoiC03wuw9drECESlD3+jPX3uPHmrCmU2CqoNKclwFM3nAI16UbWAo+Gg/SzQzyRYukoH7pittNJ0YauUIcNjprS0lWk7Wj3v+w27IannWTa4OcVAtl7mVXmcGX+/n5ejBsS/lMPOSiqXEsaQOZm1tcfJBRO75NF72UdV71SQ+YHWzvJ6HZ42WMRAgeE8ARhRdQ6CneHZE508xEh4QQPIihOCnWx3o/g+2pZFo0Um3IGOXxiR/8SCJXOtJv6yd0OpOVRAyrjXfjV9a24ZGMQ=
        on:
          tags: true
      repo: dubzzz/fast-check

