language: node_js
matrix:
  include:
    - node_js: '6'
    - node_js: '7'
    - node_js: '8'
    - node_js: '10'
      env: LEGACY_ONLY=ON
    - node_js: '10'
      env: FORMAT_ONLY=ON
    - node_js: '10'
      env: LINT_ONLY=ON
    - node_js: '10'
      env: PUBLISH_PACKAGE=ON

cache:
  directories:
  - node_modules

script:
  - CHECK_FORMAT=OFF;
    CHECK_LINT=OFF;
    CHECK_LEGACY=OFF;
  - if [ "$FORMAT_ONLY" == "ON" ] || [ "$LINT_ONLY" == "ON" ] || [ "$LEGACY_ONLY" == "ON" ];
    then
      CHECK_FORMAT=OFF;
      CHECK_LINT=OFF;
      CHECK_TEST=OFF;
      CHECK_BUILD=OFF;
      CHECK_EXAMPLE=OFF;
      CHECK_LEGACY=OFF;
      if [ "$FORMAT_ONLY" == "ON" ]; then CHECK_FORMAT=ON; fi;
      if [ "$LINT_ONLY" == "ON" ]; then CHECK_LINT=ON; fi;
      if [ "$LEGACY_ONLY" == "ON" ]; then CHECK_LEGACY=ON; fi;
    fi;
  - if [ "$PUBLISH_PACKAGE" == "ON" ];
    then
      CHECK_FORMAT=ON;
      CHECK_LINT=ON;
      CHECK_TEST=ON;
      CHECK_BUILD=ON;
      CHECK_EXAMPLE=ON;
      CHECK_LEGACY=ON;
    fi;
  - if [ "$CHECK_FORMAT" != "OFF" ]; then npm run format:check; fi;
  - if [ "$CHECK_LINT" != "OFF" ]; then npm run lint:check; fi;
  - if [ "$CHECK_TEST" != "OFF" ];
    then
      npm run test ;
      npm run e2e ;
    fi;
  - if [ "$CHECK_BUILD" != "OFF" ];
    then
      npm run build ;
      npm run webbuild ;
    fi;
  - if [ "$CHECK_EXAMPLE" != "OFF" ];
    then
      cd example ;
      bash configure.sh ;
      bash run.sh ;
      cd .. ;
    fi;
  - if [ "$CHECK_LEGACY" != "OFF" ];
      NODE_VERSION=`node --version | cut -dv -f2` ;
      nvm install 0.12 ;
      node --version ;
      node --eval "var fc = require('./lib/fast-check'); fc.assert(fc.property(fc.string(), function(s) { return s === s; }))" ;
      nvm use "${NODE_VERSION}" ;
    fi;

after_success:
  - if [ "$PUBLISH_PACKAGE" == "ON" ]; then npm run coverage; fi;

deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: U25V+vyJQn14dxiWUJ5bcsXIVM5gLxNmRvmJ8FgwyRST1tqvPk0x71rq1n0rwXJTO3aLMfEAz6499bG9MKNlwDwFBCRqDCWicbaXgAWqplaGbS3pI9EtA6aleLaS2SRET2jAT1piWtGPaXNdIQOS1ZaM+CG5RbKu0SoFDq25lPh2CrktqoR0nb2YKneWw8W7QGCuOpm11i5uLKs+7vhKOp8MVwRksHm3QgDX/+kbLVik71FEbmfn2DMna4RLCUKxeayX9/6dx+ZCD00EY5POaKNFzo29HvFaNRwNdUcPZYE97ZBDqgbs2z9KHQljBVB4cYP1lEGgTbpmPOJ9Oj8boGlf+TF/3bSK/tM0a/CKwp/L8+Fd7NSpMlLCAiMDje/3DQ5PgI5LojQzHe4zMCZO5rphoiC03wuw9drECESlD3+jPX3uPHmrCmU2CqoNKclwFM3nAI16UbWAo+Gg/SzQzyRYukoH7pittNJ0YauUIcNjprS0lWk7Wj3v+w27IannWTa4OcVAtl7mVXmcGX+/n5ejBsS/lMPOSiqXEsaQOZm1tcfJBRO75NF72UdV71SQ+YHWzvJ6HZ42WMRAgeE8ARhRdQ6CneHZE508xEh4QQPIihOCnWx3o/g+2pZFo0Um3IGOXxiR/8SCJXOtJv6yd0OpOVRAyrjXfjV9a24ZGMQ=
  on:
    condition: "$PUBLISH_PACKAGE = ON"
    tags: true
repo: dubzzz/fast-check
